# Isodisk + RT — B5 rt_source_injection activation test (minimal, no SNe).
HYDRO_MESHLESS_FINITE_MASS
COOLING
GALSF
GALSF_SFR_CRITERION=(1)
METALS
ADAPTIVE_GRAVSOFT_FORGAS
STOP_WHEN_BELOW_MINTIMESTEP
OUTPUT_ADDITIONAL_RUNINFO
RT_M1
RT_COMOVING
RT_SOURCES=48
RT_SPEEDOFLIGHT_REDUCTION=0.001
RT_OPTICAL_NIR
RT_NUV
RT_PHOTOELECTRIC
RT_CHEM_PHOTOION=1
RT_INFRARED
