#!/bin/bash
# run_compile_suite.sh — Test GIZMO compilation under many Config.sh flag combinations.
#
# Usage:
#   Local (Kokkos OpenMP):  ./test/compile_suite/run_compile_suite.sh
#   Vista (CUDA GPU):       ./test/compile_suite/run_compile_suite.sh --gpu
#   Resume after fix:       ./test/compile_suite/run_compile_suite.sh --resume
#   Resume GPU:             ./test/compile_suite/run_compile_suite.sh --gpu --resume
#
# Outputs:
#   compile_suite_results.txt — per-config pass/fail + diagnostic lines
#   compile_suite_errors/     — per-config stderr saved for failed builds

set -u

GIZMO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$GIZMO_ROOT"

NJOBS=8
GPU_MODE=0
RESUME=0
for arg in "$@"; do
    case "$arg" in
        --gpu) GPU_MODE=1 ;;
        --resume) RESUME=1 ;;
    esac
done

# Save originals (only on fresh run)
if [[ $RESUME -eq 0 ]]; then
    cp -f Config.sh Config.sh.compile_suite_backup 2>/dev/null || true
    cp -f Makefile.systype Makefile.systype.compile_suite_backup 2>/dev/null || true
fi

# Set systype based on mode
if [[ $GPU_MODE -eq 1 ]]; then
    echo 'SYSTYPE="Vista"' > Makefile.systype
    echo "[compile_suite] GPU mode: SYSTYPE=Vista"
else
    grep -q 'MacBookCellar_Kokkos' Makefile.systype.compile_suite_backup 2>/dev/null && \
        cp -f Makefile.systype.compile_suite_backup Makefile.systype || \
        echo 'SYSTYPE="MacBookCellar_Kokkos"' > Makefile.systype
    echo "[compile_suite] CPU/OpenMP mode: $(grep SYSTYPE Makefile.systype)"
fi

# Base flags prepended to every config: enable the GPU/Kokkos code path.
# GIZMO_USE_NEIGHBOR_LIST_FOR_DENSITY retired in Step 5 C5 (always-on).
# GIZMO_GPU_GRAVTREE and OPENMP_TREE_UPDATE retired in Step 5 C1/C2.
# OPENMP_GPU_OFFLOAD retired in Step 5 C4 (always-on, removed from source).
BASE_FLAGS=""

RESULTS_FILE="compile_suite_results.txt"
ERRORS_DIR="compile_suite_errors"
mkdir -p "$ERRORS_DIR"

# On fresh run, clear results
if [[ $RESUME -eq 0 ]]; then
    > "$RESULTS_FILE"
fi

# Build file of already-passed configs for resume
DONE_FILE="/tmp/compile_suite_done.$$"
> "$DONE_FILE"
if [[ $RESUME -eq 1 ]] && [[ -f "$RESULTS_FILE" ]]; then
    grep "^PASS " "$RESULTS_FILE" | sed 's/^PASS //' > "$DONE_FILE"
    ndone=$(wc -l < "$DONE_FILE" | tr -d ' ')
    echo "[compile_suite] Resuming: $ndone configs already passed, skipping those"
fi

PASS=0
FAIL=0
SKIP=0
TOTAL=0

# Configs to skip on GPU (external library dependencies)
GPU_SKIP_PATTERNS="CHIMES|COOL_GRACKLE"

# ============================================================
# Config list — mirrors test_compile_suite.py + GPU extras
# ============================================================
CONFIGS=(
    # --- FIRE defaults ---
    "FIRE_PHYSICS_DEFAULTS=1 GALSF_FB_FIRE_AGE_TRACERS=16"
    "FIRE_PHYSICS_DEFAULTS=2"
    "FIRE_PHYSICS_DEFAULTS=3"
    "FIRE_PHYSICS_DEFAULTS=2 FIRE_MHD"
    "FIRE_PHYSICS_DEFAULTS=2 FIRE_CRS=0"
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=1"
    "FIRE_PHYSICS_DEFAULTS=2 FIRE_BHS"
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_BHS FIRE_MHD FIRE_CRS=1"
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_CRS=0 FIRE_MHD FIRE_BHS"
    "FIRE_PHYSICS_DEFAULTS=2 GALSF_FB_FIRE_RPROCESS=4"
    "FIRE_PHYSICS_DEFAULTS=3 GALSF_FB_FIRE_AGE_TRACERS_CUSTOM"
    "FIRE_PHYSICS_DEFAULTS=2 OUTPUT_RECOMPUTE_POTENTIAL OUTPUT_DENS_AROUND_NONGAS OUTPUT_DELAY_TIME_HII OUTPUT_MOLECULAR_FRACTION"

    # --- FIRE + CRs ---
    "COSMIC_RAY_SUBGRID_LEBRON FIRE_PHYSICS_DEFAULTS=3 FIRE_BHS"
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 CRFLUID_ALT_REACCEL_ONLY_DIFFUSIVE FIRE_BHS"

    # --- CR fluid variations ---
    "COSMIC_RAY_FLUID"
    "COSMIC_RAY_FLUID CRFLUID_ALT_DISABLE_LOSSES"
    "COSMIC_RAY_FLUID CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=0"
    "COSMIC_RAY_FLUID MAGNETIC METALS COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=1"
    "COSMIC_RAY_FLUID MAGNETIC METALS COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=2"
    "COSMIC_RAY_FLUID METALS COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=3"
    "COSMIC_RAY_FLUID MAGNETIC COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=4"
    "COSMIC_RAY_FLUID MAGNETIC COOLING GALSF METALS CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=5"
    "COSMIC_RAY_FLUID GALSF COOLING METALS CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=6"
    "COSMIC_RAY_FLUID MAGNETIC COOLING METALS CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=7"
    "COSMIC_RAY_FLUID MAGNETIC COOLING CRFLUID_EVOLVE_SCATTERINGWAVES"

    # --- CR spectra ---
    "CRFLUID_SPEEDOFLIGHT_REDUCTION=10000 IO_MOLECFRAC_NOT_IN_ICFILE OPENMP=2 PMGRID=512 MULTIPLEDOMAINS=32 FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 BOX_PERIODIC OUTPUT_ADDITIONAL_RUNINFO FIRE_BHS"
    "CRFLUID_SPEEDOFLIGHT_REDUCTION=10000 CRFLUID_ALT_RSOL_FORM IO_MOLECFRAC_NOT_IN_ICFILE OPENMP=2 PMGRID=512 MULTIPLEDOMAINS=32 FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 BOX_PERIODIC OUTPUT_ADDITIONAL_RUNINFO"
    "CRFLUID_SPEEDOFLIGHT_REDUCTION=10000 CRFLUID_ALT_VARIABLE_RSOL IO_MOLECFRAC_NOT_IN_ICFILE OPENMP=2 PMGRID=512 MULTIPLEDOMAINS=32 FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 BOX_PERIODIC OUTPUT_ADDITIONAL_RUNINFO"
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 CRFLUID_ALT_REACCEL_ONLY_DIFFUSIVE FIRE_BHS"
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=1 CRFLUID_ALT_REACCEL_ONLY_DIFFUSIVE FIRE_BHS CRFLUID_INJECTION_AT_SHOCKS=0.1"

    # --- Single star / STARFORGE ---
    "SINGLE_STAR_AND_SSP_HYBRID_MODEL_DEFAULTS=1"
    "SINGLE_STAR_STARFORGE_DEFAULTS"
    "SINGLE_STAR_STARFORGE_DEFAULTS MAGNETIC COOLING SINGLE_STAR_FB_JETS SINGLE_STAR_FB_RAD SINGLE_STAR_FB_WINDS=0 SINGLE_STAR_FB_SNE BOX_PERIODIC GRAVITY_NOT_PERIODIC ADAPTIVE_TREEFORCE_UPDATE=0.0625"
    "SINGLE_STAR_STARFORGE_DEFAULTS COOLING MAGNETIC RT_M1 RT_INFRARED RT_SOURCES=1+16+32 RT_LYMAN_WERNER RT_PHOTOELECTRIC RT_NUV RT_FREEFREE RT_CHEM_PHOTOION=2 EOS_SUBSTELLAR_ISM"
    "SINGLE_STAR_SINK_DYNAMICS"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_TIMESTEPPING=1 EOS_GMC_BAROTROPIC"
    "SINGLE_STAR_SINK_DYNAMICS HERMITE_INTEGRATION=32"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_SINK_FORMATION=0+1+2+4+8+16+32+64"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_JETS RT_ISRF_BACKGROUND"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_WINDS=0"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_SNE"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_RT_HEATING"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_STARFORGE_PROTOSTELLAR_EVOLUTION=2 SINGLE_STAR_ACCRETION=7 SINGLE_STAR_SINK_FORMATION=0"
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=12 SINK_RETURN_ANGMOM_TO_GAS STARFORGE_GMC_TURBINIT=1 STARFORGE_FEEDBACK_TRACERS=3"
    "USE_TIMESTEP_DILATION_FOR_ZOOMS MERGESPLIT_HARDCODE_MIN_MASS=(0.5e3) MERGESPLIT_HARDCODE_MAX_MASS=(2.e3) SINGLE_STAR_AND_SSP_HYBRID_MODEL_DEFAULTS=(1.0) SINGLE_STAR_AND_SSP_NUCLEAR_ZOOM=1 SINGLE_STAR_AND_SSP_NUCLEAR_ZOOM_SPECIALBOUNDARIES=3 RT_SPEEDOFLIGHT_REDUCTION=(1.0) PMGRID=128"
    "HYDRO_MESHLESS_FINITE_MASS COOLING GALSF GALSF_SFR_CRITERION=(1+256) METALS BOX_PERIODIC GRAVITY_NOT_PERIODIC PMGRID=64 ADAPTIVE_GRAVSOFT_FORGAS OUTPUT_IN_DOUBLEPRECISION SINK_CALC_DISTANCES SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_TIMESTEPPING=0 SINGLE_STAR_FIND_BINARIES SINGLE_STAR_FB_TIMESTEPLIMIT"

    # --- Sink particles ---
    "SINK_PARTICLES"
    "SINK_PARTICLES SINK_SWALLOWGAS SINK_GRAVACCRETION=1 SINK_WIND_SPAWN=2 INPUT_READ_SINKPROPS IO_SINKS_ONLY_SNAPSHOT_FREQUENCY=0 OUTPUT_SINK_ACCRETION_HIST OUTPUT_SINK_DISTANCES OUTPUT_SINK_FORMATION_PROPS OUTPUT_UNSPAWNED_SINKMASS"
    "SINK_PARTICLES SINK_SWALLOWGAS SINK_GRAVCAPTURE_GAS SINK_GRAVCAPTURE_NONGAS SINK_GRAVCAPTURE_FIXEDSINKRADIUS SINK_REPOSITION_ON_POTMIN"
    "SINK_PARTICLES SINK_SWALLOWGAS SINK_GRAVACCRETION=1 SINK_THERMALFEEDBACK SINK_ALPHADISK_ACCRETION=10 SINK_INTERACT_ON_GAS_TIMESTEP SINK_SCALE_SPAWNINGMASS_WITH_INITIALMASS"
    "SINK_PARTICLES GALSF SINK_SWALLOWGAS SINK_GRAVACCRETION=1 SINK_WIND_KICK=1 SINK_CALC_DISTANCES SINK_GRAVACCRETION_STELLARFBCORR"
    "SINK_PARTICLES GALSF SINK_SEED_FROM_FOF=0 SINK_DYNFRICTION_FROMTREE SINK_SEED_FROM_LOCALGAS_TOTALMENCCRITERIA SINK_SUBGRIDBHVARIABILITY"
    "SINK_PARTICLES GALSF METALS SINK_SEED_FROM_LOCALGAS SINK_INCREASE_DYNAMIC_MASS=100 SINK_TEST_WIND_MIXED_FASTSLOW"
    "SINK_PARTICLES GALSF SINK_SWALLOWGAS GALSF_FB_FIRE_RT_LONGRANGE SINK_PHOTONMOMENTUM SINK_WIND_SPAWN=2 SINK_WIND_SPAWN_SET_JET_PRECESSION MAGNETIC SINK_WIND_SPAWN_SET_BFIELD_POLTOR"
    "SINK_PARTICLES RT_LEBRON RT_INFRARED METALS COOLING GALSF SINK_SWALLOWGAS SINK_HII_HEATING SINK_COMPTON_HEATING"
    "SINK_PARTICLES COSMIC_RAY_FLUID GALSF SINK_COSMIC_RAYS SINK_OUTPUT_MOREINFO SINK_WIND_SPAWN=2 SINK_CR_INJECTION_AT_TERMINATION=(0.25)"
    "OUTPUT_ADDITIONAL_RUNINFO OPENMP GALSF_MERGER_STARCLUSTER_PARTICLES SINK_RIAF_SUBEDDINGTON_MODEL FIRE_BHS FIRE_PHYSICS_DEFAULTS=3 BOX_PERIODIC PMGRID=512"

    # --- Hydro methods ---
    "HYDRO_MESHLESS_FINITE_MASS"
    "HYDRO_MESHLESS_FINITE_VOLUME"
    "HYDRO_REGULAR_GRID"
    "HYDRO_PRESSURE_SPH"
    "HYDRO_DENSITY_SPH"
    "HYDRO_GENERATE_TARGET_MESH"
    "HYDRO_FIX_MESH_MOTION=0"
    "HYDRO_FIX_MESH_MOTION=7"

    # --- Kernel / hydro options ---
    "KERNEL_FUNCTION=3"
    "KERNEL_FUNCTION=5"
    "KERNEL_FUNCTION=7"
    "KERNEL_CRK_FACES"
    "HYDRO_VOLUME_CORRECTIONS"
    "HYDRO_FACE_VOLUME_RECONSTRUCTION_CORRECTION"
    "EOS_GAMMA=1.001"
    "EOS_TILLOTSON EOS_ELASTIC"

    # --- Material / damage EOS ---
    "HYDRO_MESHLESS_FINITE_MASS SELFGRAVITY_OFF EOS_ANEOS INPUT_IN_DOUBLEPRECISION OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"
    "HYDRO_MESHLESS_FINITE_MASS BOX_SPATIAL_DIMENSION=1 BOX_PERIODIC SELFGRAVITY_OFF EOS_ANEOS INPUT_IN_DOUBLEPRECISION OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"
    "HYDRO_MESHLESS_FINITE_MASS BOX_SPATIAL_DIMENSION=2 SELFGRAVITY_OFF EOS_TILLOTSON EOS_ELASTIC EOS_DAMAGE_POROSITY=7 KERNEL_FUNCTION=6 OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"
    "HYDRO_MESHLESS_FINITE_MASS HYDRO_PARTITION_UNITY_IMPROVE_FD BOX_SPATIAL_DIMENSION=1 BOX_PERIODIC SELFGRAVITY_OFF EOS_GAMMA=(5.0/3.0) INPUT_IN_DOUBLEPRECISION OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"

    # --- Box geometry ---
    "BOX_PERIODIC"
    "BOX_BND_PARTICLES"
    "BOX_SPATIAL_DIMENSION=1"
    "BOX_SPATIAL_DIMENSION=2"
    "BOX_SHEARING=1"
    "BOX_SHEARING=3 BOX_SHEARING_Q=1."
    "BOX_LONG_X=2 BOX_LONG_Y=3 BOX_LONG_Z=3"
    "BOX_REFLECT_X=0 BOX_REFLECT_Y=0 BOX_REFLECT_Z=0"
    "BOX_OUTFLOW_X=0 BOX_OUTFLOW_Y=0 BOX_OUTFLOW_Z=0"

    # --- MHD ---
    "MAGNETIC MHD_B_SET_IN_PARAMS MHD_NON_IDEAL"
    "MAGNETIC MHD_CONSTRAINED_GRADIENT=1"
    "HYDRO_MESHLESS_FINITE_MASS BOX_PERIODIC BOX_SPATIAL_DIMENSION=2 EOS_GAMMA=(5.0/3.0) MAGNETIC MHD_B_SET_IN_PARAMS MHD_BATTERY_MECHANISMS=1 SELFGRAVITY_OFF INPUT_IN_DOUBLEPRECISION OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"
    "HYDRO_MESHLESS_FINITE_MASS BOX_PERIODIC EOS_GAMMA=(5.0/3.0) EOS_MHD_CORE_BAROTROPIC GRAVITY_NOT_PERIODIC MAGNETIC MHD_B_SET_IN_PARAMS ADAPTIVE_GRAVSOFT_FORGAS OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE TIDAL_TIMESTEP_CRITERION ADAPTIVE_TREEFORCE_UPDATE=0.06"
    "HYDRO_MESHLESS_FINITE_MASS BOX_PERIODIC BOX_SPATIAL_DIMENSION=2 OUTPUT_BFIELD_DIVCLEAN_INFO MAGNETIC SELFGRAVITY_OFF INPUT_IN_DOUBLEPRECISION OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE MHD_MODIFIED_GRADIENT"

    # --- Diffusion physics ---
    "CONDUCTION"
    "CONDUCTION CONDUCTION_SPITZER"
    "MAGNETIC CONDUCTION COOLING CONDUCTION_SPITZER"
    "VISCOSITY"
    "VISCOSITY VISCOSITY_BRAGINSKII"
    "MAGNETIC VISCOSITY COOLING VISCOSITY_BRAGINSKII"

    # --- Cooling / chemistry ---
    "COOLING"
    "COOLING METALS COOL_LOW_TEMPERATURES"
    "COOLING METALS COOL_LOW_TEMPERATURES COOL_METAL_LINES_BY_SPECIES"
    "COOLING COOLING_OPERATOR_SPLIT COOL_LOWTEMP_THIN_ONLY"
    "SINGLE_STAR_STARFORGE_DEFAULTS MAGNETIC COOLING METALS COOL_METAL_LINES_BY_SPECIES BOX_PERIODIC GRAVITY_NOT_PERIODIC ADAPTIVE_TREEFORCE_UPDATE=0.0625 TWO_TEMPERATURE_PLASMA=1"

    # --- Metals / turbulent diffusion ---
    "METALS"
    "METALS TURB_DIFF_METALS TURB_DIFF_ENERGY TURB_DIFF_VELOCITY"
    "METALS TURB_DIFF_METALS TURB_DIFF_ENERGY TURB_DIFF_VELOCITY TURB_DIFF_DYNAMIC OUTPUT_TURB_DIFF_DYNAMIC_ERROR"

    # --- Grains ---
    "GRAIN_FLUID"
    "MAGNETIC GRAIN_FLUID GRAIN_BACKREACTION GRAIN_LORENTZFORCE GRAIN_COLLISIONS"
    "HYDRO_MESHLESS_FINITE_MASS BOX_PERIODIC BOX_SPATIAL_DIMENSION=2 SELFGRAVITY_OFF EOS_TILLOTSON EOS_ELASTIC GRAIN_FLUID GRAIN_BACKREACTION GRAIN_FLUID_PROMOTION INPUT_READ_KERNELRADIUS KERNEL_FUNCTION=6 OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"
    "FIRE_PHYSICS_DEFAULTS=3 GALSF_ISMDUSTCHEM_MODEL=2"
    "MAGNETIC PIC_MHD PIC_SPEEDOFLIGHT_REDUCTION=0.01"

    # --- Gravity ---
    "PMGRID=512"
    "ADAPTIVE_GRAVSOFT_FORGAS"
    "ADAPTIVE_GRAVSOFT_FORALL=1+2+4+8+16+32"
    "SELFGRAVITY_OFF"
    "GRAVITY_NOT_PERIODIC"
    "GRAVITY_ANALYTIC"
    "GRAVITY_ACCURATE_FEWBODY_INTEGRATION"
    "EOS_TRUELOVE_PRESSURE"
    "HYDRO_MESHLESS_FINITE_MASS EOS_GAMMA=(5.0/3.0) OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE EVALPOTENTIAL"
    "HYDRO_MESHLESS_FINITE_MASS BOX_SPATIAL_DIMENSION=2 SELFGRAVITY_OFF GRAVITY_ANALYTIC GRAVITY_TESTPROBLEM_KEPLERIAN EOS_GAMMA=(7.0/5.0) ENERGY_ENTROPY_SWITCH_IS_ACTIVE OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"
    "HYDRO_MESHLESS_FINITE_MASS BOX_PERIODIC BOX_BND_PARTICLES BOX_LONG_X=1 BOX_LONG_Y=2 BOX_SPATIAL_DIMENSION=2 EOS_GAMMA=(1.4) SELFGRAVITY_OFF GRAVITY_ANALYTIC GRAVITY_TESTPROBLEM_RT OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"
    "HYDRO_MESHLESS_FINITE_MASS BOX_PERIODIC PMGRID=32 PM_HIRES_REGION_CLIPPING=1000 ADAPTIVE_GRAVSOFT_FORGAS OUTPUT_IN_DOUBLEPRECISION DEVELOPER_MODE"

    # --- Dark matter ---
    "DM_SIDM=2+4"
    "DM_SCALARFIELD_SCREENING"
    "DM_FUZZY=0"

    # --- Star formation ---
    "GALSF GALSF_SFR_IMF_VARIATION GALSF_SFR_IMF_SAMPLING_DISTRIBUTE_SF=2.0 GALSF_SFR_IMF_SAMPLING GALSF_MERGER_STARCLUSTER_PARTICLES"
    "GALSF METALS COOLING GALSF_SFR_CRITERION=0+1+2+4+32+64+128+256+512+1024 GALSF_GENERATIONS=2"
    "GALSF COOLING GALSF_EFFECTIVE_EQS GALSF_SUBGRID_WINDS GALSF_SUBGRID_WIND_SCALING=0 GALSF_FB_TURNOFF_COOLING"
    "GALSF COOLING METALS GALSF_FB_MECHANICAL GALSF_WINDS_ORIENTATION"
    "GALSF COOLING METALS GALSF_FB_THERMAL"

    # --- Radiation transport ---
    "GALSF METALS RT_FLUXLIMITEDDIFFUSION RT_SPEEDOFLIGHT_REDUCTION=0.1 RT_CHEM_PHOTOION=2 RT_OPTICAL_NIR RT_INJECT_PHOTONS_DISCRETELY RT_ISRF_BACKGROUND"
    "GALSF METALS RT_M1 RT_SOURCES=1+16+32 RT_XRAY=3 RT_LYMAN_WERNER RT_PHOTOELECTRIC RT_NUV RT_FREEFREE RT_RAD_PRESSURE_OUTPUT"
    "RT_OTVET METALS RT_INFRARED RT_GENERIC_USER_FREQ RT_DISABLE_RAD_PRESSURE RT_REPROCESS_INJECTED_PHOTONS"
    "RT_LEBRON RT_XRAY=2 RT_SEPARATELY_TRACK_LUMPOS"
    "RT_M1 METALS RT_SOURCES=1 RT_FREEFREE GRAIN_FLUID RT_OPACITY_FROM_EXPLICIT_GRAINS"
    "RT_M1 METALS RT_SOURCES=1 RT_FREEFREE RT_SELFGRAVITY_OFF OUTPUT_RT_RAD_FLUX OUTPUT_RT_RAD_OPACITY RT_COMOVING RT_DISABLE_UV_BACKGROUND RT_ENABLE_R15_GRADIENTFIX RT_ENHANCED_NUMERICAL_DIFFUSION"
    "SINGLE_STAR_STARFORGE_DEFAULTS SINGLE_STAR_STARFORGE_PROTOSTELLAR_EVOLUTION=2 COOLING BOX_PERIODIC GRAVITY_NOT_PERIODIC INPUT_READ_SINKPROPS RT_M1 RT_COMOVING OUTPUT_RT_RAD_FLUX IO_SUPPRESS_OUTPUT_EDDINGTON_TENSOR RT_SOURCES=32 RT_SPEEDOFLIGHT_REDUCTION=1.0e-4 RT_REPROCESS_INJECTED_PHOTONS RT_SINK_ANGLEWEIGHT_PHOTON_INJECTION RT_OPTICAL_NIR RT_NUV RT_PHOTOELECTRIC RT_CHEM_PHOTOION=1 RT_INFRARED RT_REINJECT_ACCRETED_PHOTONS"

    # --- FOF / Subfind ---
    "FOF SUBFIND"
    "FOF SUBFIND SUBFIND_ADDIO_NUMOVERDEN=1 SUBFIND_ADDIO_VELDISP SUBFIND_ADDIO_BARYONS"
    "BOX_PERIODIC FOF SUBFIND FOF_PRIMARY_LINK_TYPES=2 FOF_SECONDARY_LINK_TYPES=0 FOF_GROUP_MIN_SIZE=8 LINKLENGTH=0.92 INPUT_IN_DOUBLEPRECISION OUTPUT_IN_DOUBLEPRECISION"

    # --- Turbulence driving ---
    "TURB_DRIVING"
    "TURB_DRIVING BOX_PERIODIC TURB_DRIVING_SPECTRUMGRID=128"

    # --- Cosmology ---
    "GR_TABULATED_COSMOLOGY"
    "GR_TABULATED_COSMOLOGY GR_TABULATED_COSMOLOGY_W GR_TABULATED_COSMOLOGY_H GR_TABULATED_COSMOLOGY_G"

    # --- I/O options ---
    "INPUT_IN_DOUBLEPRECISION OUTPUT_POTENTIAL OUTPUT_TIDAL_TENSOR OUTPUT_ACCELERATION"
    "INPUT_POSITIONS_IN_DOUBLE OUTPUT_IN_DOUBLEPRECISION OUTPUT_CHANGEOFENERGY OUTPUT_VORTICITY"
    "COOLING OUTPUT_TIMESTEP OUTPUT_COOLRATE OUTPUT_COOLRATE_DETAIL"

    # --- Nuclear physics ---
    "HYDRO_MESHLESS_FINITE_MASS BOX_PERIODIC BOX_LONG_X=4 BOX_LONG_Y=1 BOX_LONG_Z=1 SELFGRAVITY_OFF EOS_HELMHOLTZ NUCLEAR_NETWORK NUCLEAR_NETWORK_NSE_TABLE METALS OUTPUT_IN_DOUBLEPRECISION OUTPUT_TEMPERATURE DEVELOPER_MODE STOP_WHEN_BELOW_MINTIMESTEP"
    "HYDRO_MESHLESS_FINITE_MASS BOX_SPATIAL_DIMENSION=1 BOX_PERIODIC EOS_HELMHOLTZ NUCLEAR_NETWORK NUCLEAR_NETWORK_NSE_TABLE METALS SELFGRAVITY_OFF OUTPUT_IN_DOUBLEPRECISION OUTPUT_TEMPERATURE"

    # --- Developer / debug ---
    "DEVELOPER_MODE FORCE_EQUAL_TIMESTEPS STOP_WHEN_BELOW_MINTIMESTEP"
    "FREEZE_HYDRO"
    "EOS_ENFORCE_ADIABAT=1.0001 HYDRO_REPLACE_RIEMANN_KT SLOPE_LIMITER_TOLERANCE=0"
    "ENERGY_ENTROPY_SWITCH_IS_ACTIVE PARTICLE_EXCISION"

    # --- Miscellaneous ---
    "OPENMP=2 IO_COMPRESS_HDF5 IO_SUPPRESS_TIMEBIN_STDOUT=10 OUTPUT_GRADIENT_RHO OUTPUT_GRADIENT_VEL OUTPUT_HYDROACCELERATION OUTPUT_SOFTENING OUTPUT_TEMPERATURE"
    "RT_LOCALRAYGRID=1 RT_FREEFREE"
    "OUTPUT_TWOPOINT_ENABLED"
    "BOX_PERIODIC PMGRID=512 OUTPUT_POWERSPEC"
    "MAGNETIC CONDUCTION SUPER_TIMESTEP_DIFFUSION"

    # --- Additional GPU-relevant combinations ---
    "SINGLE_STAR_STARFORGE_DEFAULTS MAGNETIC COOLING METALS COOL_METAL_LINES_BY_SPECIES BOX_PERIODIC GRAVITY_NOT_PERIODIC ADAPTIVE_TREEFORCE_UPDATE=0.0625"
    "HYDRO_MESHLESS_FINITE_VOLUME MAGNETIC COOLING METALS"
    "HYDRO_PRESSURE_SPH MAGNETIC"
    "EOS_ELASTIC EOS_TILLOTSON MAGNETIC"
    "RT_EVOLVE_INTENSITIES RT_LOCALRAYGRID=1 RT_FREEFREE METALS"

    # --- Step 13 Phase 11 newly-ported gates: regression coverage for previously-blocked flags ---
    "COUNT_MASS_IN_GRAVTREE COOLING METALS"                                              # N.3a: tree-mass diagnostic + scatter-back
    "PMGRID=64 OUTPUT_TIDAL_TENSOR BOX_PERIODIC"                                         # N.3b: shortrange_table_tidal mirror, PMGRID + tidal tensor
    "SPECIAL_POINT_MOTION SINK_PARTICLES SINK_CALC_DISTANCES"                            # N.4a: nearest-special vel/acc accumulation
    "SPECIAL_POINT_WEIGHTED_MOTION SINK_PARTICLES SINK_CALC_DISTANCES"                   # N.4a: weighted variant + GPU weight function
    "DM_SCALARFIELD_SCREENING"                                                           # N.4b: Yukawa-screened scalar-field force
    "DM_SCALARFIELD_SCREENING PMGRID=64 BOX_PERIODIC"                                    # N.4b: PMGRID variant of DM scalar field force
    "GRAVITY_SPHERICAL_SYMMETRY=0"                                                       # N.4c: shell-theorem force law
    "GRAVITY_SPHERICAL_SYMMETRY=0 OUTPUT_TIDAL_TENSOR"                                   # N.4c: shell-theorem fac2_tidal override
    "ADAPTIVE_GRAVSOFT_FORALL=1+2+4+8+16+32 ADAPTIVE_TREEFORCE_UPDATE=0.0625"            # N.5a: TIDAL+AGS_SYMMETRIZE force averaging
    "ADAPTIVE_GRAVSOFT_FROM_TIDAL_CRITERION=2 ADAPTIVE_GRAVSOFT_FORALL=1+2+4+8+16+32"    # N.5b: tidal-criterion adaptive softening + zeta correction
    "USE_TIMESTEP_DILATION_FOR_ZOOMS DILATION_FOR_STELLAR_KINEMATICS_ONLY GALSF"         # N.6a: dilation cache (KINEMATICS_ONLY: no per-node compute)
    "USE_TIMESTEP_DILATION_FOR_ZOOMS SINGLE_STAR_AND_SSP_NUCLEAR_ZOOM=1"                 # N.6a: dilation cache with NUCLEAR_ZOOM (per-node compute path)
    "SINK_PARTICLES COSMIC_RAY_FLUID GALSF SINK_COSMIC_RAYS SINK_OUTPUT_MOREINFO SINK_WIND_SPAWN=2 SINK_CR_INJECTION_AT_TERMINATION=(0.25)"  # N.6b (note: this duplicates an earlier suite config -- keeping both deliberately to verify the previously-#error'd combo works)
    "SELFGRAVITY_OFF HYDRO_MESHLESS_FINITE_MASS"                                         # N.1a: stale gate removal verification
    "SINGLE_STAR_AND_SSP_NUCLEAR_ZOOM=1 GALSF"                                           # N.5b/cache: nuclear-zoom softening via ForceSoftening cache
    "HERMITE_INTEGRATION=32 SINGLE_STAR_SINK_DYNAMICS"                                   # N.1b: HERMITE unblocked by sphere-box criterion (jerk path)
)

echo "============================================================"
echo "GIZMO Compile Suite — $(date)"
echo "Base flags: $BASE_FLAGS"
echo "Configs: ${#CONFIGS[@]}"
echo "GPU mode: $GPU_MODE"
if [[ $RESUME -eq 1 ]]; then echo "Resume mode: skipping already-passed configs"; fi
echo "============================================================"

for i in "${!CONFIGS[@]}"; do
    flags="${CONFIGS[$i]}"
    TOTAL=$((TOTAL + 1))
    label="$(echo "$flags" | cut -c1-60)"

    # Skip already-passed configs in resume mode
    if [[ $RESUME -eq 1 ]] && grep -qxF "$flags" "$DONE_FILE" 2>/dev/null; then
        PASS=$((PASS + 1))
        continue
    fi

    # Skip GPU-incompatible configs in GPU mode
    if [[ $GPU_MODE -eq 1 ]] && echo "$flags" | grep -qE "$GPU_SKIP_PATTERNS"; then
        echo "[$((i+1))/${#CONFIGS[@]}] SKIP (GPU): $label"
        echo "SKIP $flags" >> "$RESULTS_FILE"
        SKIP=$((SKIP + 1))
        continue
    fi

    printf "[$((i+1))/${#CONFIGS[@]}] %-62s " "$label..."

    # Write Config.sh with base flags + this config's flags
    {
        echo "$BASE_FLAGS"
        for flag in $flags; do
            echo "$flag"
        done
    } > Config.sh

    # Clean and build
    make clean > /dev/null 2>&1
    errfile="$ERRORS_DIR/config_$(printf '%03d' $((i+1))).stderr"
    if make -j${NJOBS} > compiler_test_stdout 2> "$errfile"; then
        echo "PASS"
        echo "PASS $flags" >> "$RESULTS_FILE"
        PASS=$((PASS + 1))
    else
        echo "FAIL"
        echo "FAIL $flags" >> "$RESULTS_FILE"
        # Capture error lines, fatal errors, and nvcc warnings 2009*/2001*
        {
            grep -iE "error:|fatal" "$errfile" 2>/dev/null | head -10
            grep -E "warning #2009|warning #2001|warning.*20011" "$errfile" 2>/dev/null | head -5
        } >> "$RESULTS_FILE"
        echo "  --- end diagnostics ---" >> "$RESULTS_FILE"
        FAIL=$((FAIL + 1))
    fi
done

# Cleanup
rm -f "$DONE_FILE"
cp -f Config.sh.compile_suite_backup Config.sh 2>/dev/null || true
cp -f Makefile.systype.compile_suite_backup Makefile.systype 2>/dev/null || true
make clean > /dev/null 2>&1

echo ""
echo "============================================================"
echo "RESULTS: $PASS pass, $FAIL fail, $SKIP skip out of $TOTAL total"
echo "Details: $RESULTS_FILE"
echo "Per-config stderr: $ERRORS_DIR/"
echo "============================================================"

if [[ $FAIL -gt 0 ]]; then
    echo ""
    echo "FAILED configs:"
    grep "^FAIL" "$RESULTS_FILE" | while IFS= read -r line; do
        echo "  ${line#FAIL }" | cut -c1-80
    done
    exit 1
fi
exit 0
