"""Compile suite test: verifies GIZMO compiles cleanly under many different Config.sh flag combinations.

This test does NOT run GIZMO -- it only checks that each configuration compiles without fatal errors.
Each row in COMPILE_CONFIGS is a list of flags to write into Config.sh. Between each, 'make clean' is run.
Success = no compile errors for any configuration.
"""

import subprocess
import sys
import os
import pytest
from pathlib import Path

# ============================================================
# List of flag combinations to test. Each entry is a string of
# space-separated flags to write into Config.sh (one per line).
# ============================================================
COMPILE_CONFIGS = [
    # --- FIRE defaults at various levels ---
    "FIRE_PHYSICS_DEFAULTS=1 GALSF_FB_FIRE_AGE_TRACERS=16",
    "FIRE_PHYSICS_DEFAULTS=2",
    "FIRE_PHYSICS_DEFAULTS=3",
    "FIRE_PHYSICS_DEFAULTS=2 FIRE_MHD",
    "FIRE_PHYSICS_DEFAULTS=2 FIRE_CRS=0",
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=1",
    "FIRE_PHYSICS_DEFAULTS=2 FIRE_BHS",
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_BHS FIRE_MHD FIRE_CRS=1",
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_CRS=0 FIRE_MHD FIRE_BHS",
    "FIRE_PHYSICS_DEFAULTS=2 GALSF_FB_FIRE_RPROCESS=4",
    "FIRE_PHYSICS_DEFAULTS=3 GALSF_FB_FIRE_AGE_TRACERS_CUSTOM",
    "FIRE_PHYSICS_DEFAULTS=2 OUTPUT_RECOMPUTE_POTENTIAL OUTPUT_DENS_AROUND_NONGAS OUTPUT_DELAY_TIME_HII OUTPUT_MOLECULAR_FRACTION",

    # --- FIRE + CRs ---
    "COSMIC_RAY_SUBGRID_LEBRON FIRE_PHYSICS_DEFAULTS=3 FIRE_BHS",
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 CRFLUID_ALT_REACCEL_ONLY_DIFFUSIVE FIRE_BHS",

    # --- CR fluid variations ---
    "COSMIC_RAY_FLUID",
    "COSMIC_RAY_FLUID CRFLUID_ALT_DISABLE_LOSSES",
    "COSMIC_RAY_FLUID CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=0",
    "COSMIC_RAY_FLUID MAGNETIC METALS COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=1",
    "COSMIC_RAY_FLUID MAGNETIC METALS COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=2",
    "COSMIC_RAY_FLUID METALS COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=3",
    "COSMIC_RAY_FLUID MAGNETIC COOLING CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=4",
    "COSMIC_RAY_FLUID MAGNETIC COOLING GALSF METALS CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=5",
    "COSMIC_RAY_FLUID GALSF COOLING METALS CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=6",
    "COSMIC_RAY_FLUID MAGNETIC COOLING METALS CRFLUID_SPEEDOFLIGHT_REDUCTION=500 CRFLUID_DIFFUSION_MODEL=7",
    "COSMIC_RAY_FLUID MAGNETIC COOLING CRFLUID_EVOLVE_SCATTERINGWAVES",

    # --- CR spectra ---
    "CRFLUID_SPEEDOFLIGHT_REDUCTION=10000 IO_MOLECFRAC_NOT_IN_ICFILE OPENMP=2 PMGRID=512 MULTIPLEDOMAINS=32 FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 BOX_PERIODIC OUTPUT_ADDITIONAL_RUNINFO FIRE_BHS",
    "CRFLUID_SPEEDOFLIGHT_REDUCTION=10000 CRFLUID_ALT_RSOL_FORM IO_MOLECFRAC_NOT_IN_ICFILE OPENMP=2 PMGRID=512 MULTIPLEDOMAINS=32 FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 BOX_PERIODIC OUTPUT_ADDITIONAL_RUNINFO",
    "CRFLUID_SPEEDOFLIGHT_REDUCTION=10000 CRFLUID_ALT_VARIABLE_RSOL IO_MOLECFRAC_NOT_IN_ICFILE OPENMP=2 PMGRID=512 MULTIPLEDOMAINS=32 FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 BOX_PERIODIC OUTPUT_ADDITIONAL_RUNINFO",
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=2 CRFLUID_ALT_REACCEL_ONLY_DIFFUSIVE FIRE_BHS",
    "FIRE_PHYSICS_DEFAULTS=3 FIRE_MHD FIRE_CRS=0 CRFLUID_EVOLVE_SPECTRUM=1 CRFLUID_ALT_REACCEL_ONLY_DIFFUSIVE FIRE_BHS CRFLUID_INJECTION_AT_SHOCKS=0.1",

    # --- Single star / STARFORGE ---
    "SINGLE_STAR_AND_SSP_HYBRID_MODEL_DEFAULTS=1",
    "SINGLE_STAR_STARFORGE_DEFAULTS",
    "SINGLE_STAR_STARFORGE_DEFAULTS MAGNETIC COOLING SINGLE_STAR_FB_JETS SINGLE_STAR_FB_RAD SINGLE_STAR_FB_WINDS=0 SINGLE_STAR_FB_SNE BOX_PERIODIC GRAVITY_NOT_PERIODIC ADAPTIVE_TREEFORCE_UPDATE=0.0625",
    "SINGLE_STAR_STARFORGE_DEFAULTS COOLING MAGNETIC RT_M1 RT_INFRARED RT_SOURCES=1+16+32 RT_LYMAN_WERNER RT_PHOTOELECTRIC RT_NUV RT_FREEFREE RT_CHEM_PHOTOION=2 EOS_SUBSTELLAR_ISM",
    "SINGLE_STAR_SINK_DYNAMICS",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_TIMESTEPPING=1 EOS_GMC_BAROTROPIC",
    "SINGLE_STAR_SINK_DYNAMICS HERMITE_INTEGRATION=32",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_SINK_FORMATION=0+1+2+4+8+16+32+64",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_JETS RT_ISRF_BACKGROUND",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_WINDS=0",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_SNE",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=7 SINGLE_STAR_FB_RT_HEATING",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_STARFORGE_PROTOSTELLAR_EVOLUTION=2 SINGLE_STAR_ACCRETION=7 SINGLE_STAR_SINK_FORMATION=0",
    "SINGLE_STAR_SINK_DYNAMICS SINGLE_STAR_ACCRETION=12 SINK_RETURN_ANGMOM_TO_GAS STARFORGE_GMC_TURBINIT=1 STARFORGE_FEEDBACK_TRACERS=3",

    # --- Sink particles ---
    "SINK_PARTICLES",
    "SINK_PARTICLES SINK_SWALLOWGAS SINK_GRAVACCRETION=1 SINK_WIND_SPAWN=2 INPUT_READ_SINKPROPS IO_SINKS_ONLY_SNAPSHOT_FREQUENCY=0 OUTPUT_SINK_ACCRETION_HIST OUTPUT_SINK_DISTANCES OUTPUT_SINK_FORMATION_PROPS OUTPUT_UNSPAWNED_SINKMASS",
    "SINK_PARTICLES SINK_SWALLOWGAS SINK_GRAVCAPTURE_GAS SINK_GRAVCAPTURE_NONGAS SINK_GRAVCAPTURE_FIXEDSINKRADIUS SINK_REPOSITION_ON_POTMIN",
    "SINK_PARTICLES SINK_SWALLOWGAS SINK_GRAVACCRETION=1 SINK_THERMALFEEDBACK SINK_ALPHADISK_ACCRETION=10 SINK_INTERACT_ON_GAS_TIMESTEP SINK_SCALE_SPAWNINGMASS_WITH_INITIALMASS",
    "SINK_PARTICLES GALSF SINK_SWALLOWGAS SINK_GRAVACCRETION=1 SINK_WIND_KICK=1 SINK_CALC_DISTANCES SINK_GRAVACCRETION_STELLARFBCORR",
    "SINK_PARTICLES GALSF SINK_SEED_FROM_FOF=0 SINK_DYNFRICTION_FROMTREE SINK_SEED_FROM_LOCALGAS_TOTALMENCCRITERIA SINK_SUBGRIDBHVARIABILITY",
    "SINK_PARTICLES GALSF METALS SINK_SEED_FROM_LOCALGAS SINK_INCREASE_DYNAMIC_MASS=100 SINK_TEST_WIND_MIXED_FASTSLOW",
    "SINK_PARTICLES GALSF SINK_SWALLOWGAS GALSF_FB_FIRE_RT_LONGRANGE SINK_PHOTONMOMENTUM SINK_WIND_SPAWN=2 SINK_WIND_SPAWN_SET_JET_PRECESSION MAGNETIC SINK_WIND_SPAWN_SET_BFIELD_POLTOR",
    "SINK_PARTICLES RT_LEBRON RT_INFRARED METALS COOLING GALSF SINK_SWALLOWGAS SINK_HII_HEATING SINK_COMPTON_HEATING",
    "SINK_PARTICLES COSMIC_RAY_FLUID GALSF SINK_COSMIC_RAYS SINK_OUTPUT_MOREINFO SINK_WIND_SPAWN=2 SINK_CR_INJECTION_AT_TERMINATION=(0.25)",

    # --- Hydro methods ---
    "HYDRO_MESHLESS_FINITE_MASS",
    "HYDRO_MESHLESS_FINITE_VOLUME",
    "HYDRO_REGULAR_GRID",
    "HYDRO_PRESSURE_SPH",
    "HYDRO_DENSITY_SPH",
    "HYDRO_GENERATE_TARGET_MESH",
    "HYDRO_FIX_MESH_MOTION=0",
    "HYDRO_FIX_MESH_MOTION=7",

    # --- Kernel / hydro options ---
    "KERNEL_FUNCTION=3",
    "KERNEL_FUNCTION=5",
    "KERNEL_FUNCTION=7",
    "KERNEL_CRK_FACES",
    "HYDRO_VOLUME_CORRECTIONS",
    "HYDRO_FACE_VOLUME_RECONSTRUCTION_CORRECTION",
    "EOS_GAMMA=1.001",
    "EOS_TILLOTSON EOS_ELASTIC",

    # --- Box geometry ---
    "BOX_PERIODIC",
    "BOX_BND_PARTICLES",
    "BOX_SPATIAL_DIMENSION=1",
    "BOX_SPATIAL_DIMENSION=2",
    "BOX_SHEARING=1",
    "BOX_SHEARING=3 BOX_SHEARING_Q=1.",
    "BOX_LONG_X=2 BOX_LONG_Y=3 BOX_LONG_Z=3",
    "BOX_REFLECT_X=0 BOX_REFLECT_Y=0 BOX_REFLECT_Z=0",
    "BOX_OUTFLOW_X=0 BOX_OUTFLOW_Y=0 BOX_OUTFLOW_Z=0",

    # --- MHD ---
    "MAGNETIC MHD_B_SET_IN_PARAMS MHD_NON_IDEAL",
    "MAGNETIC MHD_CONSTRAINED_GRADIENT=1",

    # --- Diffusion physics ---
    "CONDUCTION",
    "CONDUCTION CONDUCTION_SPITZER",
    "MAGNETIC CONDUCTION COOLING CONDUCTION_SPITZER",
    "VISCOSITY",
    "VISCOSITY VISCOSITY_BRAGINSKII",
    "MAGNETIC VISCOSITY COOLING VISCOSITY_BRAGINSKII",

    # --- Cooling / chemistry ---
    "COOLING",
    "COOLING METALS COOL_LOW_TEMPERATURES",
    "COOLING METALS COOL_LOW_TEMPERATURES COOL_METAL_LINES_BY_SPECIES",
    "COOLING COOLING_OPERATOR_SPLIT COOL_LOWTEMP_THIN_ONLY",

    # --- Metals / turbulent diffusion ---
    "METALS",
    "METALS TURB_DIFF_METALS TURB_DIFF_ENERGY TURB_DIFF_VELOCITY",
    "METALS TURB_DIFF_METALS TURB_DIFF_ENERGY TURB_DIFF_VELOCITY TURB_DIFF_DYNAMIC OUTPUT_TURB_DIFF_DYNAMIC_ERROR",

    # --- Grains ---
    "GRAIN_FLUID",
    "MAGNETIC GRAIN_FLUID GRAIN_BACKREACTION GRAIN_LORENTZFORCE GRAIN_COLLISIONS",
    "MAGNETIC PIC_MHD PIC_SPEEDOFLIGHT_REDUCTION=0.01",

    # --- Gravity ---
    "PMGRID=512",
    "ADAPTIVE_GRAVSOFT_FORGAS",
    "ADAPTIVE_GRAVSOFT_FORALL=1+2+4+8+16+32",
    "SELFGRAVITY_OFF",
    "GRAVITY_NOT_PERIODIC",
    "GRAVITY_ANALYTIC",
    "GRAVITY_ACCURATE_FEWBODY_INTEGRATION",
    "EOS_TRUELOVE_PRESSURE",

    # --- Dark matter ---
    "DM_SIDM=2+4",
    "DM_SCALARFIELD_SCREENING",
    "DM_FUZZY=0",

    # --- Star formation ---
    "GALSF GALSF_SFR_IMF_VARIATION GALSF_SFR_IMF_SAMPLING_DISTRIBUTE_SF=2.0 GALSF_SFR_IMF_SAMPLING GALSF_MERGER_STARCLUSTER_PARTICLES",
    "GALSF METALS COOLING GALSF_SFR_CRITERION=0+1+2+4+32+64+128+256+512+1024 GALSF_GENERATIONS=2",
    "GALSF COOLING GALSF_EFFECTIVE_EQS GALSF_SUBGRID_WINDS GALSF_SUBGRID_WIND_SCALING=0 GALSF_FB_TURNOFF_COOLING",
    "GALSF COOLING METALS GALSF_FB_MECHANICAL GALSF_WINDS_ORIENTATION",
    "GALSF COOLING METALS GALSF_FB_THERMAL",

    # --- Radiation transport ---
    "GALSF METALS RT_FLUXLIMITEDDIFFUSION RT_SPEEDOFLIGHT_REDUCTION=0.1 RT_CHEM_PHOTOION=2 RT_OPTICAL_NIR RT_INJECT_PHOTONS_DISCRETELY RT_ISRF_BACKGROUNDs",
    "GALSF METALS RT_M1 RT_SOURCES=1+16+32 RT_XRAY=3 RT_LYMAN_WERNER RT_PHOTOELECTRIC RT_NUV RT_FREEFREE RT_RAD_PRESSURE_OUTPUT",
    "RT_OTVET METALS RT_INFRARED RT_GENERIC_USER_FREQ RT_DISABLE_RAD_PRESSURE RT_REPROCESS_INJECTED_PHOTONS",
    "RT_LEBRON RT_XRAY=2 RT_SEPARATELY_TRACK_LUMPOS",
    "RT_M1 METALS RT_SOURCES=1 RT_FREEFREE GRAIN_FLUID RT_OPACITY_FROM_EXPLICIT_GRAINS",
    "RT_M1 METALS RT_SOURCES=1 RT_FREEFREE RT_SELFGRAVITY_OFF OUTPUT_RT_RAD_FLUX OUTPUT_RT_RAD_OPACITY RT_COMOVING RT_DISABLE_UV_BACKGROUND RT_ENABLE_R15_GRADIENTFIX RT_ENHANCED_NUMERICAL_DIFFUSION",

    # --- FOF / Subfind ---
    "FOF SUBFIND",
    "FOF SUBFIND SUBFIND_ADDIO_NUMOVERDEN=1 SUBFIND_ADDIO_VELDISP SUBFIND_ADDIO_BARYONS",

    # --- Turbulence driving ---
    "TURB_DRIVING",
    "TURB_DRIVING BOX_PERIODIC TURB_DRIVING_SPECTRUMGRID=128",

    # --- Cosmology ---
    "GR_TABULATED_COSMOLOGY",
    "GR_TABULATED_COSMOLOGY GR_TABULATED_COSMOLOGY_W GR_TABULATED_COSMOLOGY_H GR_TABULATED_COSMOLOGY_G",

    # --- I/O options ---
    "INPUT_IN_DOUBLEPRECISION OUTPUT_POTENTIAL OUTPUT_TIDAL_TENSOR OUTPUT_ACCELERATION",
    "INPUT_POSITIONS_IN_DOUBLE OUTPUT_IN_DOUBLEPRECISION OUTPUT_CHANGEOFENERGY OUTPUT_VORTICITY",
    "COOLING OUTPUT_TIMESTEP OUTPUT_COOLRATE OUTPUT_COOLRATE_DETAIL",

    # --- Developer / debug ---
    "DEVELOPER_MODE FORCE_EQUAL_TIMESTEPS STOP_WHEN_BELOW_MINTIMESTEP",
    "FREEZE_HYDRO",
    "EOS_ENFORCE_ADIABAT=1.0001 HYDRO_REPLACE_RIEMANN_KT SLOPE_LIMITER_TOLERANCE=0",
    "ENERGY_ENTROPY_SWITCH_IS_ACTIVE PARTICLE_EXCISION",

    # --- CHIMES ---
    #"GALSF CHIMES METALS COOLING COOL_METAL_LINES_BY_SPECIES CHIMES_REDUCED_OUTPUT CHIMES_NH_OUTPUT",

    # --- Grackle ---
    #"COOLING COOL_GRACKLE",
    #"GALSF METALS COOLING COOL_GRACKLE COOL_GRACKLE_CHEMISTRY=2",

    # --- Miscellaneous ---
    "OPENMP=2 IO_COMPRESS_HDF5 IO_SUPPRESS_TIMEBIN_STDOUT=10 OUTPUT_GRADIENT_RHO OUTPUT_GRADIENT_VEL OUTPUT_HYDROACCELERATION OUTPUT_SOFTENING OUTPUT_TEMPERATURE",
    "RT_LOCALRAYGRID=1 RT_FREEFREE",
    "METALS OUTPUT_LINEOFSIGHT OUTPUT_LINEOFSIGHT_PARTICLES OUTPUT_LINEOFSIGHT_SPECTRUM",
    "OUTPUT_TWOPOINT_ENABLED", 
    "BOX_PERIODIC PMGRID=512 OUTPUT_POWERSPEC",
    "MAGNETIC CONDUCTION SUPER_TIMESTEP_DIFFUSION",
]


def _gizmo_root() -> Path:
    """Return the GIZMO root directory (2 levels up from this test file)."""
    return Path(__file__).resolve().parent.parent.parent


def _write_config(flags: str, config_path: Path):
    """Write a Config.sh with one flag per line."""
    with open(config_path, "w") as f:
        for flag in flags.split():
            f.write(flag + "\n")


def _make_clean(gizmo_root: Path):
    """Run make clean."""
    subprocess.run(["make", "clean"], cwd=gizmo_root,
                   capture_output=True, timeout=60)


def _make_build(gizmo_root: Path, timeout: int = 600) -> subprocess.CompletedProcess:
    """Run make -j and return the result."""
    return subprocess.run(
        ["make", f"-j{os.cpu_count() or 4}"],
        cwd=gizmo_root,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


@pytest.mark.parametrize("flags", COMPILE_CONFIGS, ids=[
    c.split()[0][:40] + ("..." if len(c.split()) > 1 else "")
    for c in COMPILE_CONFIGS
])
def test_compile(flags):
    """Test that GIZMO compiles cleanly with the given Config.sh flags."""
    gizmo_root = _gizmo_root()
    config_path = gizmo_root / "Config.sh"

    # Write Config.sh
    _write_config(flags, config_path)

    # Clean
    _make_clean(gizmo_root)

    # Build
    result = _make_build(gizmo_root)

    # Check for fatal errors (not warnings)
    errors = []
    if result.returncode != 0:
        for line in (result.stderr or "").split("\n"):
            if "error:" in line.lower() and "warning" not in line.lower():
                errors.append(line.strip())
        if "ld:" in (result.stderr or ""):
            for line in (result.stderr or "").split("\n"):
                if "Undefined symbols" in line or "ld: symbol" in line:
                    errors.append(line.strip())

    # Clean up
    _make_clean(gizmo_root)

    assert result.returncode == 0 and not errors, (
        f"Compile FAILED for flags: {flags}\n"
        f"Return code: {result.returncode}\n"
        f"Errors:\n" + "\n".join(errors[:20])
    )
