# isodisk_mechfb + explicit M1 radiation transport from the stars (isodisk_mechfb_rt.params).
# RT_SOURCES=48: star and sink particles (types 4,5) are the radiation sources.
HYDRO_MESHLESS_FINITE_MASS
COOLING
GALSF
GALSF_SFR_CRITERION=(1+256)
METALS
GALSF_FB_MECHANICAL
BOX_PERIODIC
PMGRID=64
ADAPTIVE_GRAVSOFT_FORGAS
STOP_WHEN_BELOW_MINTIMESTEP
RT_M1
RT_COMOVING
RT_SOURCES=48
RT_SPEEDOFLIGHT_REDUCTION=0.001
RT_OPTICAL_NIR
RT_NUV
RT_PHOTOELECTRIC
RT_CHEM_PHOTOION=1
RT_INFRARED
