# Select Target Computer
#
# Please copy this file to Makefile.systype and uncomment your
# system. Don't commit changes to this file unless you add support for
# a new system.
#
#############

#SYSTYPE="github-ubuntu"
#SYSTYPE="Frontera"
#SYSTYPE="MacBookCellar"
SYSTYPE="MacBookCellar_Kokkos"
#SYSTYPE="Vista"
#SYSTYPE="Expanse"
#SYSTYPE="CaltechHPC"
#SYSTYPE="RUSTY"
